import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from myLib import calibrate_hazard_curve, survival_probs

RECOVERY_RATE = 0.4
LGD = 1 - RECOVERY_RATE


def main():

    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    DATA_PATH = os.path.join(BASE_DIR, "data", "raw", "market_data2.xlsx")
    OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    data = pd.read_excel(DATA_PATH,
                        header = 1,
                        index_col= 0,
                        usecols= 'B:H',
                        nrows = 11)
    data = data.sort_index()

    #recovering dfs corresponding to the maturities in the data
    DFS_PATH = os.path.join(BASE_DIR, "data", "processed", "discount_factors.csv")
    dfs = pd.read_csv(DFS_PATH, index_col= 0) #Load discount factors generated by zcb_curve.py

    maturities = data.index.to_numpy(dtype = float)
    dfs = dfs.loc[maturities].to_dict()[dfs.columns[0]]

    #hazard rates calibration for each firm
    hazard_rates = {}
    for firm in data.columns:
        spreads = data.loc[maturities, firm] / 10000

        hazard_rates[firm] = calibrate_hazard_curve(maturities, spreads, dfs)

    hazard_rates_table = pd.DataFrame(hazard_rates, index=maturities)

    print("\nHazard Rates DataFrame:")
    print(hazard_rates_table)

    #survival and default probabilities calculation for each firm
    survival_probabilities = {}
    default_probabilities = {}
    for firm in hazard_rates_table.columns:
        lambdas = hazard_rates_table[firm].to_numpy()
        times = hazard_rates_table.index.to_numpy()

        q = survival_probs(lambdas, times)

        survival_probabilities[firm] = q
        default_probabilities[firm] = 1 - np.array(q)

    survival_probabilities_table = pd.DataFrame(survival_probabilities, index=maturities)
    default_probabilities_table = pd.DataFrame(default_probabilities, index=maturities)

    print("\nSurvival Probabilities DataFrame:")
    print(survival_probabilities_table)

    print("\nDefault Probabilities DataFrame:")
    print(default_probabilities_table)

    fig, ax = plt.subplots()
    for firm in survival_probabilities_table.columns:
        ax.plot(maturities,
                survival_probabilities_table[firm],
                label=f'Survival - {firm}')
    ax.set_xlabel('Maturity (years)')
    ax.set_ylabel('Survival Probability')
    ax.set_title('Survival Probabilities over Time')
    ax.legend()
    ax.grid()
    plt.savefig(os.path.join(OUTPUT_DIR, "survival_probabilities_plot.png"))

    fig, ax = plt.subplots()
    for firm in default_probabilities_table.columns:
        ax.plot(maturities,
                default_probabilities_table[firm],
                label=f'Default - {firm}') 
    ax.set_xlabel('Maturity (years)')
    ax.set_ylabel('Default Probability')
    ax.set_title('Default Probabilities over Time')
    ax.legend()
    ax.grid()
    plt.savefig(os.path.join(OUTPUT_DIR, "default_probabilities_plot.png"))

    hazard_rates_table.to_csv(os.path.join(OUTPUT_DIR, "hazard_rates.csv"))
    survival_probabilities_table.to_csv(os.path.join(OUTPUT_DIR, "survival_probabilities.csv"))
    default_probabilities_table.to_csv(os.path.join(OUTPUT_DIR, "default_probabilities.csv"))

    plt.show()


if __name__ == "__main__":
    main()